  var PARKS = [
    { id:1, name:"Bend-Sunriver RV Campground", city:"Bend", st:"OR", network:"tt", region:"Northwest" },
    { id:2, name:"Pacific City RV & Camping Resort", city:"Cloverdale", st:"OR", network:"tt", region:"Northwest" },
    { id:3, name:"Seaside RV Resort", city:"Seaside", st:"OR", network:"tt", region:"Northwest" },
    { id:4, name:"Whalers Rest RV & Camping Resort", city:"South Beach", st:"OR", network:"tt", region:"Northwest" },
    { id:5, name:"South Jetty RV & Camping Resort", city:"Florence", st:"OR", network:"tt", region:"Northwest" },
    { id:6, name:"La Conner RV & Camping Resort", city:"La Conner", st:"WA", network:"tt", region:"Northwest" },
    { id:7, name:"Grandy Creek RV Campground", city:"Concrete", st:"WA", network:"tt", region:"Northwest" },
    { id:8, name:"Crescent Bar RV Resort", city:"Quincy", st:"WA", network:"tt", region:"Northwest" },
    { id:9, name:"Chehalis RV & Camping Resort", city:"Chehalis", st:"WA", network:"tt", region:"Northwest" },
    { id:10, name:"Birch Bay RV Campground", city:"Blaine", st:"WA", network:"tt", region:"Northwest" },
    { id:11, name:"Leavenworth RV Campground", city:"Leavenworth", st:"WA", network:"tt", region:"Northwest" },
    { id:12, name:"Little Diamond RV Campground", city:"Newport", st:"WA", network:"tt", region:"Northwest" },
    { id:13, name:"Long Beach RV & Camping Resort", city:"Seaview", st:"WA", network:"tt", region:"Northwest" },
    { id:14, name:"Thunderbird RV & Camping Resort", city:"Monroe", st:"WA", network:"tt", region:"Northwest" },
    { id:15, name:"Paradise RV Campground", city:"Silver Creek", st:"WA", network:"tt", region:"Northwest" },
    { id:16, name:"Oceana RV & Camping Resort", city:"Ocean City", st:"WA", network:"tt", region:"Northwest" },
    { id:17, name:"Mount Vernon RV Campground", city:"Bow", st:"WA", network:"tt", region:"Northwest" },
    { id:18, name:"Cultus Lake RV Resort", city:"Lindell Beach", st:"BC", network:"tt", region:"Northwest" },
    { id:19, name:"Moody Beach RV Campground", city:"Wells", st:"ME", network:"tt", region:"Northeast" },
    { id:20, name:"Sturbridge RV Resort", city:"Sturbridge", st:"MA", network:"tt", region:"Northeast" },
    { id:21, name:"Gateway to Cape Cod", city:"Rochester", st:"MA", network:"tt", region:"Northeast" },
    { id:22, name:"Sea Pines RV Resort & Campground", city:"Swainton", st:"NJ", network:"tt", region:"Northeast" },
    { id:23, name:"Lake & Shore RV Resort", city:"Ocean View", st:"NJ", network:"tt", region:"Northeast" },
    { id:24, name:"Chestnut Lake RV Campground", city:"Port Republic", st:"NJ", network:"tt", region:"Northeast" },
    { id:25, name:"Rondout Valley RV Campground", city:"Accord", st:"NY", network:"tt", region:"Northeast" },
    { id:26, name:"Scotrun RV Resort", city:"Scotrun", st:"PA", network:"tt", region:"Northeast" },
    { id:27, name:"PA Dutch Country RV Resort", city:"Manheim", st:"PA", network:"tt", region:"Northeast" },
    { id:28, name:"Hershey RV & Camping Resort", city:"Lebanon", st:"PA", network:"tt", region:"Northeast" },
    { id:29, name:"Gettysburg Farm RV Campground", city:"Dover", st:"PA", network:"tt", region:"Northeast" },
    { id:30, name:"Circle M RV & Camping Resort", city:"Lancaster", st:"PA", network:"tt", region:"Northeast" },
    { id:31, name:"Timothy Lake South RV", city:"East Stroudsburg", st:"PA", network:"tt", region:"Northeast" },
    { id:32, name:"Timothy Lake North RV", city:"East Stroudsburg", st:"PA", network:"tt", region:"Northeast" },
    { id:33, name:"Medina Lake RV Campground", city:"Lakehills", st:"TX", network:"tt", region:"Southeast" },
    { id:34, name:"Colorado River RV Campground", city:"Columbus", st:"TX", network:"tt", region:"Southeast" },
    { id:35, name:"Lake Conroe RV & Camping Resort", city:"Willis", st:"TX", network:"tt", region:"Southeast" },
    { id:36, name:"Lake Whitney RV Campground", city:"Whitney", st:"TX", network:"tt", region:"Southeast" },
    { id:37, name:"Bay Landing RV Campground", city:"Bridgeport", st:"TX", network:"tt", region:"Southeast" },
    { id:38, name:"Lake Texoma RV Campground", city:"Gordonville", st:"TX", network:"tt", region:"Southeast" },
    { id:39, name:"Lake Tawakoni RV Campground", city:"Point", st:"TX", network:"tt", region:"Southeast" },
    { id:40, name:"Cherokee Landing Campground", city:"Middleton", st:"TN", network:"tt", region:"Southeast" },
    { id:41, name:"Natchez Trace RV Campground", city:"Hohenwald", st:"TN", network:"tt", region:"Southeast" },
    { id:42, name:"Hidden Cove Resort", city:"Arley", st:"AL", network:"tt", region:"Southeast" },
    { id:43, name:"Carolina Landing RV Resort", city:"Fair Play", st:"SC", network:"tt", region:"Southeast" },
    { id:44, name:"The Oaks at Point South RV", city:"Yemassee", st:"SC", network:"tt", region:"Southeast" },
    { id:45, name:"Green Mountain Park", city:"Lenoir", st:"NC", network:"tt", region:"Southeast" },
    { id:46, name:"Forest Lake RV & Camping Resort", city:"Advance", st:"NC", network:"tt", region:"Southeast" },
    { id:47, name:"Lake Gaston RV & Camping Resort", city:"Littleton", st:"NC", network:"tt", region:"Southeast" },
    { id:48, name:"Lynchburg RV Resort", city:"Gladys", st:"VA", network:"tt", region:"Southeast" },
    { id:49, name:"Williamsburg RV & Camping Resort", city:"Williamsburg", st:"VA", network:"tt", region:"Southeast" },
    { id:50, name:"Harbor View RV & Camping Resort", city:"Colonial Beach", st:"VA", network:"tt", region:"Southeast" },
    { id:51, name:"Chesapeake Bay RV Resort", city:"Gloucester", st:"VA", network:"tt", region:"Southeast" },
    { id:52, name:"Virginia Landing RV Campground", city:"Quinby", st:"VA", network:"tt", region:"Southeast" },
    { id:53, name:"Three Flags RV Campground", city:"Wildwood", st:"FL", network:"tt", region:"Southeast" },
    { id:54, name:"Orlando RV Resort", city:"Clermont", st:"FL", network:"tt", region:"Southeast" },
    { id:55, name:"Peace River RV & Camping Resort", city:"Wauchula", st:"FL", network:"tt", region:"Southeast" },
    { id:56, name:"Verde Valley RV & Camping Resort", city:"Cottonwood", st:"AZ", network:"tt", region:"Southwest" },
    { id:57, name:"Snowflower RV Resort", city:"Emigrant Gap", st:"CA", network:"tt", region:"Southwest" },
    { id:58, name:"Lake of the Springs RV Resort", city:"Oregon House", st:"CA", network:"tt", region:"Southwest" },
    { id:59, name:"Lake Minden RV Resort", city:"Nicolaus", st:"CA", network:"tt", region:"Southwest" },
    { id:60, name:"Idyllwild RV Resort", city:"Idyllwild", st:"CA", network:"tt", region:"Southwest" },
    { id:61, name:"Morgan Hill RV Resort", city:"Morgan Hill", st:"CA", network:"tt", region:"Southwest" },
    { id:62, name:"Oakzanita Springs RV Campground", city:"Descanso", st:"CA", network:"tt", region:"Southwest" },
    { id:63, name:"San Benito RV & Camping Resort", city:"Paicines", st:"CA", network:"tt", region:"Southwest" },
    { id:64, name:"Russian River RV Campground", city:"Cloverdale", st:"CA", network:"tt", region:"Southwest" },
    { id:65, name:"Rancho Oso RV & Camping Resort", city:"Santa Barbara", st:"CA", network:"tt", region:"Southwest" },
    { id:66, name:"Ponderosa RV Resort", city:"Lotus", st:"CA", network:"tt", region:"Southwest" },
    { id:67, name:"Pio Pico RV Resort & Campground", city:"Jamul", st:"CA", network:"tt", region:"Southwest" },
    { id:68, name:"Palm Springs RV Resort", city:"Palm Desert", st:"CA", network:"tt", region:"Southwest" },
    { id:69, name:"Yosemite Lakes RV Resort", city:"Groveland", st:"CA", network:"tt", region:"Southwest" },
    { id:70, name:"Wilderness Lakes RV Resort", city:"Menifee", st:"CA", network:"tt", region:"Southwest" },
    { id:71, name:"Turtle Beach RV Resort", city:"Manteca", st:"CA", network:"tt", region:"Southwest" },
    { id:72, name:"Soledad Canyon RV & Camping Resort", city:"Acton", st:"CA", network:"tt", region:"Southwest" },
    { id:73, name:"Blue Mesa Recreational Ranch", city:"Gunnison", st:"CO", network:"tt", region:"Southwest" },
    { id:74, name:"Las Vegas RV Resort", city:"Las Vegas", st:"NV", network:"tt", region:"Southwest" },
    { id:75, name:"Pine Country RV & Camping Resort", city:"Belvidere", st:"IL", network:"tt", region:"Midwest" },
    { id:76, name:"Indian Lakes RV Campground", city:"Batesville", st:"IN", network:"tt", region:"Midwest" },
    { id:77, name:"Horseshoe Lakes RV Campground", city:"Clinton", st:"IN", network:"tt", region:"Midwest" },
    { id:78, name:"Diamond Caverns RV & Golf Club", city:"Park City", st:"KY", network:"tt", region:"Midwest" },
    { id:79, name:"Bear Cave RV Campground", city:"Buchanan", st:"MI", network:"tt", region:"Midwest" },
    { id:80, name:"St Clair RV Resort", city:"Saint Clair", st:"MI", network:"tt", region:"Midwest" },
    { id:81, name:"Wilmington RV Resort", city:"Wilmington", st:"OH", network:"tt", region:"Midwest" },
    { id:82, name:"Kenisee Lake RV Campground", city:"Jefferson", st:"OH", network:"tt", region:"Midwest" },
    { id:83, name:"Araby Acres RV Resort", city:"", st:"AZ", network:"enc", region:"Trails Collection" },
    { id:84, name:"Cactus Gardens RV Resort", city:"", st:"AZ", network:"enc", region:"Trails Collection" },
    { id:85, name:"Capri RV Resort", city:"", st:"AZ", network:"enc", region:"Trails Collection" },
    { id:86, name:"Casita Verde RV Resort", city:"", st:"AZ", network:"enc", region:"Trails Collection" },
    { id:87, name:"Countryside RV Resort", city:"", st:"AZ", network:"enc", region:"Trails Collection" },
    { id:88, name:"Desert Paradise RV Resort", city:"", st:"AZ", network:"enc", region:"Trails Collection" },
    { id:89, name:"Fiesta Grande RV Resort", city:"", st:"AZ", network:"enc", region:"Trails Collection" },
    { id:90, name:"Foothill Village RV Resort", city:"", st:"AZ", network:"enc", region:"Trails Collection" },
    { id:91, name:"Foothills West RV Resort", city:"", st:"AZ", network:"enc", region:"Trails Collection" },
    { id:92, name:"Golden Sun RV Resort", city:"", st:"AZ", network:"enc", region:"Trails Collection" },
    { id:93, name:"Meridian RV Resort", city:"", st:"AZ", network:"enc", region:"Trails Collection" },
    { id:94, name:"Mesa Spirit RV Resort", city:"", st:"AZ", network:"enc", region:"Trails Collection" },
    { id:95, name:"Mesa Verde RV Resort", city:"", st:"AZ", network:"enc", region:"Trails Collection" },
    { id:96, name:"Monte Vista Village RV Resort", city:"", st:"AZ", network:"enc", region:"Trails Collection" },
    { id:97, name:"Paradise RV Resort", city:"", st:"AZ", network:"enc", region:"Trails Collection" },
    { id:98, name:"Suni Sands RV Resort", city:"", st:"AZ", network:"enc", region:"Trails Collection" },
    { id:99, name:"Valley Vista RV Resort", city:"", st:"AZ", network:"enc", region:"Trails Collection" },
    { id:100, name:"Venture In RV Resort", city:"", st:"AZ", network:"enc", region:"Trails Collection" },
    { id:101, name:"ViewPoint RV & Golf Resort", city:"", st:"AZ", network:"enc", region:"Trails Collection" },
    { id:102, name:"Voyager RV Resort & Hotel", city:"", st:"AZ", network:"enc", region:"Trails Collection" },
    { id:103, name:"Marina Dunes RV Resort", city:"", st:"CA", network:"enc", region:"Trails Collection" },
    { id:104, name:"Oceanside RV Resort", city:"", st:"CA", network:"enc", region:"Trails Collection" },
    { id:105, name:"Pacific Dunes Ranch RV Resort", city:"", st:"CA", network:"enc", region:"Trails Collection" },
    { id:106, name:"Palm Springs Oasis RV Resort", city:"", st:"CA", network:"enc", region:"Trails Collection" },
    { id:107, name:"Pilot Knob RV Resort", city:"", st:"CA", network:"enc", region:"Trails Collection" },
    { id:108, name:"San Francisco RV Resort", city:"", st:"CA", network:"enc", region:"Trails Collection" },
    { id:109, name:"Santa Cruz Ranch RV Resort", city:"", st:"CA", network:"enc", region:"Trails Collection" },
    { id:110, name:"Tahoe Valley Campground", city:"", st:"CA", network:"enc", region:"Trails Collection" },
    { id:111, name:"Barrington Hills RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:112, name:"Breezy Hill RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:113, name:"Bulow RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:114, name:"Clerbrook Golf & RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:115, name:"Clover Leaf Forest RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:116, name:"Crystal Isles RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:117, name:"Fiesta Key RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:118, name:"Forest Lake Village", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:119, name:"Fort Myers Beach RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:120, name:"Gulf Air RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:121, name:"Gulf View RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:122, name:"Harbor Lakes RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:123, name:"Highland Woods RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:124, name:"Holiday Travel Park", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:125, name:"Lake Magic RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:126, name:"Miami Everglades RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:127, name:"Pioneer Village RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:128, name:"Ramblers Rest RV Campground", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:129, name:"Riverside RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:130, name:"Rose Bay RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:131, name:"Royal Coachman RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:132, name:"Sherwood Forest RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:133, name:"Silver Dollar RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:134, name:"Southern Palms RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:135, name:"Space Coast RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:136, name:"Sunshine Holiday Daytona", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:137, name:"Sunshine Holiday Ft. Lauderdale", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:138, name:"Sunshine Key RV Resort & Marina", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:139, name:"Sunshine Travel RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:140, name:"Terra Ceia RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:141, name:"Toby's RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:142, name:"Topics RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:143, name:"Tranquility Lakes RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:144, name:"Tropical Palms RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:145, name:"Vacation Village RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:146, name:"Winter Garden RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:147, name:"Winter Quarters Manatee RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:148, name:"Winter Quarters Pasco RV Resort", city:"", st:"FL", network:"enc", region:"Trails Collection" },
    { id:149, name:"O'Connell's RV Campground", city:"", st:"IL", network:"enc", region:"Trails Collection" },
    { id:150, name:"Twin Mills Camping Resort", city:"", st:"IN", network:"enc", region:"Trails Collection" },
    { id:151, name:"Mt Desert Narrows Camping Resort", city:"", st:"ME", network:"enc", region:"Trails Collection" },
    { id:152, name:"Narrows Too Camping Resort", city:"", st:"ME", network:"enc", region:"Trails Collection" },
    { id:153, name:"Patten Pond Camping Resort", city:"", st:"ME", network:"enc", region:"Trails Collection" },
    { id:154, name:"Pinehirst RV Resort & Campground", city:"", st:"ME", network:"enc", region:"Trails Collection" },
    { id:155, name:"Old Chatham Road RV Campground", city:"", st:"MA", network:"enc", region:"Trails Collection" },
    { id:156, name:"Pine Acres Resort", city:"", st:"NH", network:"enc", region:"Trails Collection" },
    { id:157, name:"Sandy Beach RV & Camping Resort", city:"", st:"NH", network:"enc", region:"Trails Collection" },
    { id:158, name:"Tuxbury Pond RV Resort", city:"", st:"NH", network:"enc", region:"Trails Collection" },
    { id:159, name:"Acorn Campground", city:"", st:"NJ", network:"enc", region:"Trails Collection" },
    { id:160, name:"Echo Farms Campground", city:"", st:"NJ", network:"enc", region:"Trails Collection" },
    { id:161, name:"King Nummy Trail Campground", city:"", st:"NJ", network:"enc", region:"Trails Collection" },
    { id:162, name:"Mays Landing Campground", city:"", st:"NJ", network:"enc", region:"Trails Collection" },
    { id:163, name:"Whippoorwill Campground", city:"", st:"NJ", network:"enc", region:"Trails Collection" },
    { id:164, name:"Alpine Lake RV Resort", city:"", st:"NY", network:"enc", region:"Trails Collection" },
    { id:165, name:"Brennan Beach RV Resort", city:"", st:"NY", network:"enc", region:"Trails Collection" },
    { id:166, name:"Lake George Escape Campground", city:"", st:"NY", network:"enc", region:"Trails Collection" },
    { id:167, name:"Lake George Schroon Valley Resort", city:"", st:"NY", network:"enc", region:"Trails Collection" },
    { id:168, name:"Harbor Point RV Park", city:"", st:"NC", network:"enc", region:"Trails Collection" },
    { id:169, name:"Lake Myers RV & Camping Resort", city:"", st:"NC", network:"enc", region:"Trails Collection" },
    { id:170, name:"Twin Lakes RV & Camping Resort", city:"", st:"NC", network:"enc", region:"Trails Collection" },
    { id:171, name:"Whispering Pines Campground", city:"", st:"NC", network:"enc", region:"Trails Collection" },
    { id:172, name:"White Oak Shores", city:"", st:"NC", network:"enc", region:"Trails Collection" },
    { id:173, name:"Mt Hood Village RV Resort", city:"", st:"OR", network:"enc", region:"Trails Collection" },
    { id:174, name:"Portland Fairview RV Park", city:"", st:"OR", network:"enc", region:"Trails Collection" },
    { id:175, name:"Appalachian RV Campground", city:"", st:"PA", network:"enc", region:"Trails Collection" },
    { id:176, name:"Drummer Boy Camping Resort", city:"", st:"PA", network:"enc", region:"Trails Collection" },
    { id:177, name:"Robin Hill RV Resort & Campground", city:"", st:"PA", network:"enc", region:"Trails Collection" },
    { id:178, name:"Round Top Campground", city:"", st:"PA", network:"enc", region:"Trails Collection" },
    { id:179, name:"Spring Gulch RV Resort", city:"", st:"PA", network:"enc", region:"Trails Collection" },
    { id:180, name:"Sun Valley RV Resort", city:"", st:"PA", network:"enc", region:"Trails Collection" },
    { id:181, name:"Alamo Palms RV Resort", city:"", st:"TX", network:"enc", region:"Trails Collection" },
    { id:182, name:"Country Sunshine RV Resort", city:"", st:"TX", network:"enc", region:"Trails Collection" },
    { id:183, name:"Fun-N-Sun RV Resort", city:"", st:"TX", network:"enc", region:"Trails Collection" },
    { id:184, name:"Lakewood RV Resort", city:"", st:"TX", network:"enc", region:"Trails Collection" },
    { id:185, name:"Leisure World RV Resort", city:"", st:"TX", network:"enc", region:"Trails Collection" },
    { id:186, name:"Paradise Park RV Resort", city:"", st:"TX", network:"enc", region:"Trails Collection" },
    { id:187, name:"Paradise South RV Resort", city:"", st:"TX", network:"enc", region:"Trails Collection" },
    { id:188, name:"Southern Comfort RV Resort", city:"", st:"TX", network:"enc", region:"Trails Collection" },
    { id:189, name:"Sunshine RV Resort", city:"", st:"TX", network:"enc", region:"Trails Collection" },
    { id:190, name:"Trails End RV Resort", city:"", st:"TX", network:"enc", region:"Trails Collection" },
    { id:191, name:"Tropic Winds RV Resort", city:"", st:"TX", network:"enc", region:"Trails Collection" },
    { id:192, name:"Victoria Palms RV Resort", city:"", st:"TX", network:"enc", region:"Trails Collection" },
    { id:193, name:"Bethpage Camp-Resort", city:"", st:"VA", network:"enc", region:"Trails Collection" },
    { id:194, name:"Grey's Point Camp", city:"", st:"VA", network:"enc", region:"Trails Collection" },
    { id:195, name:"Tall Chief RV & Camping Resort", city:"", st:"WA", network:"enc", region:"Trails Collection" },
    { id:196, name:"Arrowhead RV Campground", city:"", st:"WI", network:"enc", region:"Trails Collection" },
    { id:197, name:"Blackhawk Camping Resort", city:"", st:"WI", network:"enc", region:"Trails Collection" },
    { id:198, name:"Fremont RV Resort", city:"", st:"WI", network:"enc", region:"Trails Collection" },
    { id:199, name:"Lake of the Woods Campground", city:"", st:"WI", network:"enc", region:"Trails Collection" },
    { id:200, name:"Lakeland Camping Resort", city:"", st:"WI", network:"enc", region:"Trails Collection" },
    { id:201, name:"Neshonoc Lakeside Camping Resort", city:"", st:"WI", network:"enc", region:"Trails Collection" },
    { id:202, name:"Plymouth Rock Camping Resort", city:"", st:"WI", network:"enc", region:"Trails Collection" },
    { id:203, name:"Tranquil Timbers Camping Resort", city:"", st:"WI", network:"enc", region:"Trails Collection" },
    { id:204, name:"Yukon Trails RV & Camping Resort", city:"", st:"WI", network:"enc", region:"Trails Collection" }
  ];
